---
{{- if .Values.sealedSecrets.enabled }}
{{- $namespace := .Values.namespace | default .Release.Namespace  }}
{{- $labels := include "testserver.labels" . }}
{{- range .Values.sealedSecrets.secrets }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  {{- with .secretAnnotations }}
  annotations: {{ toYaml . | nindent 6 }}
  {{- end }}
  name: {{ .secretName }}
  namespace: {{ $namespace }}
spec:
  encryptedData: {{ toYaml .encryptedData | nindent 6}}
  template:
    metadata:
      {{- with .secretAnnotations }}
      annotations: {{ toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- $labels | nindent 8 }}
      name: {{ .secretName }}
      namespace: {{ $namespace }}
    type: Opaque
{{- end }}
{{- end }}
