{{- if and .Values.persistence.enabled .Values.persistence.snapshots -}}
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: new-snapshot-test
spec:
  volumeSnapshotClassName: csi-trident-snapclass
  source:
    persistentVolumeClaimName: "{{ .Values.persistence.data.claimName }}"
{{- end -}}
