kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ include "postgresql.fullname" . }}-allow-egress-to-minio
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: postgresql
  egress:
    - to:
        - podSelector:
            matchLabels:
              app: minio
          namespaceSelector:
            matchLabels:
              customer: dpc-oa
  policyTypes:
    - Egress
