# Dev configuaration
#
image:
  tag: 0.9.8
  
replicaCount: 1

env:
  - name: SECRET_KEY
    value: DevHelmChartSecret
  - name: ENV
    value: 'Dev'
  - name: REDIS_PASSWORD
    value: cEPguKSbSp
  - name: REDIS_SERVER
    value: redis

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    # traefik.ingress.kubernetes.io/router.middlewares: testserver-testserver-stripprefix@kubernetescrd
  className: nginx
  hosts:
    - host: testserver.dev.gerull.nl
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: testserver
              port:
                number: 80
