{{- if .Values.genericSecrets.enabled }}
{{- range .Values.genericSecrets.secrets }}
apiVersion: v1
stringData:
  {{ .key }}: {{ .value }}
kind: Secret
metadata:
  name: {{ .name }}
type: Opaque
---
{{- end }}
{{- end }}
