# Testserver Reviewomgeving Configuaration
#
global:
  featureFlags:
    postgresql: false
    redis: true

testserver:

  replicaCount: 2

  env:
    - name: SECRET_KEY
      valueFrom:
        secretKeyRef:
          name: testserver
          key: SECRET_KEY
    - name: ENV
      value: 'Reviewomgeving'
    - name: REDIS_SERVER
      value: testapp-redis-master
    - name: REDIS_PASSWORD
      valueFrom:
        secretKeyRef:
          name: redisserver
          key: REDIS_PASSWORD

  genericSecrets:
    enabled: true
    secrets:
      - name: testserver
        key: SECRET_KEY
        value: GenricChartSecret
      - name: redisserver
        key: REDIS_PASSWORD
        value: vMm6lo4lBo

  securityContext: {}

  ingress:
    enabled: true
    # annotations:
    #   # nginx.ingress.kubernetes.io/ssl-redirect: "false"
    #   traefik.ingress.kubernetes.io/router.middlewares: testserver-testserver-stripprefix@kubernetescrd
    ingressClassName: nginx
    hosts:
      - host: testserver-clgr.reviewomgeving.nl
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: testserver
                port:
                  number: 80
