# Dev local configuaration
#
image:
  tag: "0.9.11"

replicaCount: 1

service:
  port: 80

env:
  - name: SECRET_KEY
    value: DevHelmChartSecret
  - name: ENV
    value: "k3d-dev environment"

ingress:
  enabled: true
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
  hosts:
    - host: testserver.dev.local
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: testserver
              port:
                number: 80
