# Dev local configuaration
#
image:
  tag: "0.9.13"

replicaCount: 1

# -- Horizontal scaling settings.
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50
  # targetMemoryUtilizationPercentage: 70

service:
  port: 80

env:
  - name: SECRET_KEY
    value: DevHelmChartSecret
  - name: ENV
    value: "dev-local"

# volumeMounts:
#   - mountPath: /run/secret/my-secret
#     name: testsecret

ingress:
  enabled: true
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
  hosts:
    - host: testserver.dev.local
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: testserver
              port:
                number: 80

persistence:
  enabled: false
  snapshots: false
  volumes:
    - name: testserver-data
      mountPath: /data
      claimName: testserver-data
      storageClass: "local-path"
      size: 512M
      accessMode: ReadWriteMany

localSecrets:
  enabled: true
  secrets:
    - name: testsecret
      secretName: testserver
      mountPath: /run/secret/my-secret
