apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: testserver
  namespace: argocd
spec:
  project: default
  destination:
    namespace: testserver
    server: https://kubernetes.default.svc
  source:
    path: kubernetes/pi-cluster
    repoURL: https://github.com/cgerull/deploy-test-server
    targetRevision: HEAD
    directory:
      recurse: true
      jsonnet: {}
  syncPolicy:
    automated:
      selfHeal: true
