apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: testserver-example
spec:
  secretStoreRef:
    name: secrets-acc-solvinity-net
    kind: SecretStore
  target:
    name: testserver
  data:
  - secretKey: testserver
    remoteRef:
      key: container-platform-acc/testserver
      property: my_secret