{{- range .Values.mysql.secretManagerSecrets }}
---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: {{ .name }}
spec:
  backendType: secretsManager
  {{- if .roleArn }}
  roleArn: {{ .roleArn | quote }}
  {{- end }}
  data:
    {{- toYaml .data | nindent 4 }}
{{- end }}
