# Dev configuaration
#
image:
  tag: 1.0.0

replicaCount: 2

env:
  - name: SECRET_KEY
    value: DevHelmChartSecret
  - name: ENV
    value: 'Dev'
  # - name: REDIS_PASSWORD
  #   value: cEPguKSbSp
  # - name: REDIS_SERVER
  #   value: redis

ingress:
  enabled: true
  annotations:
    # nginx.ingress.kubernetes.io/ssl-redirect: "false"
    traefik.ingress.kubernetes.io/router.middlewares: testserver-testserver-stripprefix@kubernetescrd
  className: traefik
  hosts:
    - host: testserver.dieren.gerull.nl
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: testserver
              port:
                number: 80
