# Dev configuaration
#
image:
  tag: 1.0.0

replicaCount: 1

securityContext:
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70

env:
  - name: SECRET_KEY
    value: PiHelmChartSecret
  # - name: SECRET_FILE
  #   value: "/run/secrets/testsecret"
  - name: ENV
    value: 'pi-cluster'
  # - name: REDIS_PASSWORD
  #   value: cEPguKSbSp
  # - name: REDIS_SERVER
  #   value: redis

ingress:
  enabled: true
  annotations:
    # nginx.ingress.kubernetes.io/ssl-redirect: "false"
    traefik.ingress.kubernetes.io/router.middlewares: testserver-testserver-stripprefix@kubernetescrd
  className: traefik
  hosts:
    - host: testserver.dieren.gerull.nl
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: testserver
              port:
                number: 80

persistence:
  enabled: true
  snapshots: false
  volumes:
    - name: instance
      mountPath: /home/web/instance
      claimName: instance-data
      storageClass: "longhorn"
      size: 250Mi
      accessMode: ReadWriteMany

tmpfs:
  enabled: false

localSecrets:
  enabled: false
  secrets:
    - name: testsecret
      mountPath: /run/secret/my-secret
      secretName: my_secret