{{ if eq .Values.global.cluster "test7" }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: {{ .Release.Name }}-cnpg-user-secret
spec:
  encryptedData:
    password: AgCMbop2qdjMYWwhRAiTI3jYoEiuASpUB5YWHfLHYKpBVbR6KT+xTYnijM9Tg051Id4ZfzLA/UmZmvfQczv/MMElTz39W1YjAJkMy1kuJDw6xvwZUs3sozV1T/MWV53OQYWbn6r0oMqDXjD1vTDW3qTDrXsbpeajzqhaLKt3ktGnO/3BuD6Y4qA8GUoyRSZ2xiYcxbYwyEbGW/U7Cz+WMF1Lx7IP9f4/S3JvgjK5oGf7vhXuPCCkTk6GEVtGffkgdAvGddbRuVpCVq7jSkauggK8AWk015zC9TOpkJx6choc3ZhkbinPl4InbloEvzmE7gvFimUrm5ZGJkPypt/3vWPNudMgZEBnJW+EAa1IrGBv6eAI2d7RmwTJZZZMkJbcKoj008WEZhQA1GnSfUVA3nxZ4Bp/xPkZu0QYQk8RWL5l29ehOGmueeKJJl4QDQ9yLfbjjn/HfptlgWDkg+dkmfncPKpwg7eGmKMPknTL7qXr1Hu7f9qvO58HZfuOGi1CsNb7rXm3RY8FKEGfPzt9r3mCmCrgn2bTqspHQnSLu+HkyjlEPSZ+/5eyRZ7TJZVyWbFSDhthy2ycVCC2kW7bJau6KwGhy9h0UObM/w8GnJY21kgIomD0ql7NAWKqmXyzBJT3UmYNOZG7UoWeGwfVO7c3zi3+Db6EVs8/EXM+rdzm4Uk4eIDPUsZB9yupfOlhHO1FhJV9aNLPH7Z0MDxmGDkhyEtHfgU=
    username: AgCbDU6qwClLrDnTM4LqhSEv4eyT71rR3D85rNqnPej7xYfodgr4dKyDQHdps3S7HScuTM0Edx/lfpMxepCK4kAU/rXhqwlc6pBfbXZ9OW0EettH/qWDDbuCf9gA3umbKixLMexhV/BDn+Uy+Ovn7Qspm2CEH9tDK4C3MWfzag43KK9O8zTs34/hnS/FYTKuBkIqh4/TxfuV6YmxCVDs9FtOhA2ugX6jnBhAY8HA6S31KWqQMueR3E0LYT/knUN+zbLVsQ7R7TBzvo7GmN4AcSKAyb2ihkFESakDQUUqV8RL5qmh06vlt4/xfDT8MPrZlaq5vd9EYCz6zaO/2SE+7icwzdcwzfcZOeT/BhltrocikWBXO1bNCWS2mAy7hfLVyXEEfvOxausmykSm0HQb3ULzxOzZ6jETn4vniTxGGgOO0sSutj7oGqWqJztWVZj3bvVT7w6n/X0zos3sl1kFzSaV/wK6KYW4QmbRNl15N2/SVy50v3Og+HBFahi8ZRAxUhznQCDaRiCVcQCCj5ahHQPF5Pl4G8Dqj6eb83LwhW4xn6OyqeTmpAa9asrKLNdXIiuEKYsQ3Lg4Qdqyy5uhWDhleT+tdzp+/tMyMMBEWWog9D+ZjWVNjVx4NdHMcliP43XMX+wBu8z651K7qkwzjN+1l1dKNauL2ZRR8Ct1PfrUmBL16pRuuTIF3BStKr6jK5jxglcxtdE=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: {{ .Release.Name }}-cnpg-user-secret
    type: kubernetes.io/basic-auth
{{ end }}
---
{{ if eq .Values.global.cluster "prod7" }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: {{ .Release.Name }}-cnpg-user-secret
spec:
  encryptedData:
    password: AgDeM2o592UgFdq2vgMMxT67Elsj8vw89Cs8Rc94M56uuxKgkJHnM1xqmVulNJWS4yOpgxoF5/HgoW4GU6pPrlZj/xVIDZV5bBWw/ntJ2OAO3p9omjyE11ElfQRZK7f7qiAg+4JhI3jodiyl512wA50mr0c46Y+C1VQkr+VU4jkWaDio1iRsdEHpm4WoHFZNofC/jTHO4lM9oytfo76bQJBibhQnHtbLla5xUlf+P80D8gEsr3TAd+GCh6KL5Aco1lOSaDwd3ZbAkUxqSJo3kr9jyAtv3TsFZW4E1sg9THx+QbQw9jpnIIqGTMYByOmG0uQo1t8cI4Gp7+DM8sZuHrpJsbnTAOTXzCE7dekhHPalIYpv2BpJ7IkUQ7Zu1Sz5hgxjPuhF/djdbhjQ2a2VrdOPT7pU3e2Vw282jTZlZQYzRDQLjrau/Klp0j0uVBtG/V4VnRx9hIr/aA8M4L82rma+Ie36Je63eGlBvAfUOxMVhRRCD6qVM77OqN6xbg0xPt4OMc4EpDeM3hFHojCTYtQHvHwcGIWPJiXy66jCHfCyEbTO/K44GnuTgBFPmi/dCBcUT99t8l5xgecIvMSAbBww6TsSznZrpVRE//eU5RrCxgkNxnfP+KgZf8EFQuS+W6nrO6+l93t+vsLCKVzAQKeBTp7r85svU04FWdMT5Xt3e7la2SsIjCJ0+WqDuLxGGrR1sQ1qqYHLw8cSEJ7ePOD/Cywg4RI=
    username: AgDDvVjUbFmQRBHk/IwG0de5gvTlfy5g22tytc7pYFku9kiankRWqvuhjX2hu5ahnDy+1dIeCyaBhLTBJA8275Pn4eeQNpsjUfOSsFLtZlRduGr7zQD6G2uq6rxK7lIV29+T11c1DxLhuFdanVGIPNcZpZ+haBRM7ltaHXCZb1k0+iuNT4Hbe24+QPhpKwffisrR6HX8y2kRtZRntvfGrIOOinx3kz94syQVK8Sy5oFTfAaiZLwvTMV33qqXm1ip1OqNmsQC1dEzFuZA5LhDjZEN1ohGY/xgyn4OL/GdNusaSFqh2791LU8nwffLqv/BsbSq4B9fxcXW4+6vFk9JyKEpBrN8A2wR+87pI6KvZ1zrSvHVjKjKJze1CAUBcQ9rXpbB7p+YhrhOVkXBzK0npudO/ghHH3+c4HYJ1cORg3nVBE6wjTX1DAvMVo8Rs1tPmOvW5OEFQv+L8AwZ6t5/bOu5ON8JpYtF9Y5jAN2DFUx/VS19tLoVbDEdxI/STJUrfQMSF8+VAhpvaP6je6Z1BXEYFRQHmzXGuh7l124ORAlSgde4XDMYKE5U+x4UoSu1VAMUvYVFsOe7Y2q6A4l9AjkQcMB63CGIPjyoO9x3fn63gJ+Hk0zbuOcvh04LhPYYRuAqHt0u7afdQcTpG+bz4RagHm/qUPJJpVqZtLnnyxp+xA/MoMqgKb/vOSDzwUz/I+Aaf/lXjs0=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: {{ .Release.Name }}-cnpg-user-secret
    type: kubernetes.io/basic-auth
{{ end }}
