{{ if eq .Values.global.cluster "test7" }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: {{ .Release.Name }}-cnpg-superuser-secret
spec:
  encryptedData:
    password: AgB5OlMRX1OvxL3vQDAGaqfqWDFd5Et7As3jdkK0Yyp/H8Q2KLTm6wsKQm/QdyxwNODnce3QuYKy8W8nnZ62o6wuojVco4cWfUcLSRkSZ7bQGNBSuY+thVTSFpHk47pxP8PhkY2NMyNe4WTodREKluH/afZHKPEdBJ1HuL7cqCKKWbe22KnXvNyiaRXheXtvTJOcFYOpOLSKLy59Ml8lx1pi+eRP8IunNhwrMCwoXB+UL6dOUzDo/vZ8GRhthOetojnyvY+PIkgGwN6CkfLw+MGesI9JN2I6GBl0wiVNUKj02c0uXqV/39dhsIvcr1E6BSr9SQig3q1ga9Zz1ZEvUdUTO75kTCj4Kli1kXStJ33fB146UK879YBnABZy4ueCZp+KcRGzi2xX8wDSab0KjQ4Z5qT0yMnaDABNc4ouocfQ5KqVWu2edO5AqcKUJ7FxBHfl9LIqqthbeLeIfXuninzSfdmw3jCKfyjbwtohMTtqYdk+0wUtCURtgQ8kQw3EyYzb1ZKnwAOWe52hxv0IVz9DCrwS3Xxh/zQZCXJBzcshhaQqUrSy/vZowaf5RIf618tzjRCcFFKAMO+27jb9bk1EeIbXXjHVr62S3x8+i5z8+ACUCzOoORBji9gaMN2SNaOxcFy0gdJJ6cNYn8+7/EAYA90bkyNKiumQq2qinHx9booNQkFFa4UGwFAibDoJpqw6/ZcMSZm8
    username: AgBcbuQgMrdbEVs6X7UpgAHKxq3ZLVKGZCOGSFJ+HzRosCVHcgU41iu2YEWjMxgY3H1kkdL8nefYRPveFVTowPtQVbvX9xMnMq4dUe5zsnrW72wRM8RKxAoHincg0C2e10hztAirCYCpq9MqQ6AxYPjddAMxXofAsHWVrlnGXbfB7qWqFps26Qm04Ou1N73JYaG4pQi1VMYn2ekzWHFrSApvTlI5KFVLlVFuWYTMryG8XEAZnYT00wDikl5tzGv7M8QuJ328YnNPznL0zj1Wq40cPmzoI9AQULgNkYJf4lTPhmCg4dipTnbmWnpApOIJPF5JbzU3e1YnEy/0SHRdwucOxa+ft4/5z0h1PDg+dXaLzJ7gVDRMpCLKozw++DbHsqGjVa7CrOqVmHoIHmgsAlPB91gRgi/hEa65cKepjrSvwnX61uopJeIxjMmXzEeVbxToQLgZAEEcAfqTnvnAx+LkFWHV9pRd5NuL42sk1Q/q1JxtVK8zj88eCVdrxnb34Ab/p1kIi2kAdqnuqRG/iTNunlW3oTK5YmQaIEWsDDFOfwsiAv5aTaDBQHvyIzJTzJP8p7SZQc2IERFIx9Eq21z4oebFOdE6Bul1aL3/F/1A/AmiMvp7YCz7GmbPOTEcnpfX/9kh53e7qwfIG6/Xjyeu0oWq4boROHOwTg+PWaORQCWK6l6GpCf9IxaZ+0/BTxt3AiskT3sSjQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: {{ .Release.Name }}-cnpg-superuser-secret
{{ end }}
---
{{ if eq .Values.global.cluster "prod7" }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: {{ .Release.Name }}-cnpg-superuser-secret
spec:
  encryptedData:
    password: AgAiMSXXyck9Ki86IaqaXyusCOwwcNcwNGMuHaKsKRRBV6cXtzG4qulnYlzbCyPbEXjYgvszEGrUYm4SC3C8nGe/ZEohdKxkwDAoe6ubCAtzCwPvuxdHIe3t/DuKy3T2z1IveMlPt74ESiPLO26qWZGPkJ5VWot0EA4fj7ioyYkHoPcab35wuWXwgYPFyxQk/ObBNtKKUbS8SJ3jLtP1HVjctPOt+8/YpWJFikrVeW1QcW3BKt2Pf4c7mHwpHh4YNKPHDdKx5h23YQ3hXFyIs0NHfD35yYZLVrQjlIz9tvvKGtK1rDI7Nc8U849a04lgySYsTslPkSzjvGriygbQyrCzYc+THfzXPrrx0Bwov4vVnZP2ptlJvIQL1P4ToG2xHFd00HE0iakkH0s3zlJUGxdJsGOevgPUlr/fmgqHMGKZXgLTjjDVi1qHVI/CzpVOCcVSfElKvqoRPUibFcxd2v8xkIIVADHStD5caePl9A+XqEy82B641OM6p/1hiqR7WKnjY9oGyBTkKy0NVfeimlbMpObBSYLa2A3+TyK5ru86brAd4KOAZ53Nm1436XjVtLZKaulybPFW2aLqxYFDQZcXS9Q2sYKngEAfnNAu8Wld9s+43ND4vZdGk3mlCz0QkIFBuHPf4ibq17FXS1zWagFqOU8GDIQWo9vRHVtjlDBPIn/EZHvAmAugC5qwqNVsR8r/JXhVYqkH
    username: AgCfjBiL6xXj3NZBiDxWBct1wdmrt1d2RKpIqWmpHoNTeNYE81HTGChzf89uXZjy4CXfkHP9mSPzlUrkqAofZmxvvs1beBwBYLoYcGDmaEyhWHetF3FOe2LHAbvTtuVm1/OoRz5y3NXNzoiDfbZWMvyp1uFgeMUy1pmRtXyWIBp5B+SudzdK9MHS6VEf4U4yr8t6HSv30n/5/DBsMQnlOMQQeRaiMNe73vryZscsagVPHtdBYGF3V+jbF4M0Q/RTyOZFFH5F/w+8xPnkDgb/kkssE+MAwaTCdQ7kcljcs98xPreQ97PHdlnKt6+XkSkQjtB9DV6vKUbjkIRrG6ZCYh9mxLC5eB9xN+Di/ZFFSR8qzDlirXxZfsk2YRYUV03t+zhUnUJakMANFjj+iHbTRAQRIHQi1OSxWowB1EwReXFK8CByUaDpF8yL212ekc/WzYulMrc4feIX1iIoKwGTVuA4hrBmlZSRXS+f1InavnjPJ6WUSHo4yjc8jrRkwIo7LZoHj1O2Cq9BO/YGR5EqpZU9tPmSfQ9+QkubU/4UGfS5cAUNDshdBzoKxdw7DcPTdlvGVO8qhoPOiRtuYI15hWVGBxAdQOJ6RasO/ja5dkDi01akE/xu6QGyYWWflne45TjxMrY8AsphYJd71qVp0dicuMk7MKozSotCzoKCDqZuJBa1G/JtgSfMUHXAa9hY+ZyBe+JY8SxQxw==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: {{ .Release.Name }}-cnpg-superuser-secret
  {{ end }}
