apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: testserver-minikube
  namespace: argocd
spec:
  destination:
    namespace: testerver-helm
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
  sources:
    - repoURL: https://gitlab.com/api/v4/projects/34978775/packages/helm/stable
      chart: testserver
      targetRevision: 0.9.51
      helm:
        valueFiles:
        - $values/dev-local/testserver.yaml
    - repoURL: https://github.com/cgerull/deploy-config
      targetRevision: HEAD
      ref: values
