global:
  featureFlags:
    postgresql: false
    redis: true

testserver:
  image:
  tag: 1.0.1

  env:
    - name: SECRET_KEY
      value: DevHelmChartSecret
    - name: ENV
      value: 'Dev'
    - name: REDIS_PASSWORD
      value: cEPguKSbSp
    - name: REDIS_SERVER
      value: testapp-redis-master

  ingress:
    enabled: true
    annotations: {}
    hosts:
      - host: testserver-clgr.origin.p25e.nl
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: testserver
                port:
                  number: 80

redis:
  auth:
    password: cEPguKSbSp
