apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: testsuite
  namespace: argocd
spec:
  description: This Project contains configuration for the Dev environment.
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    server: '*'
  orphanedResources:
    warn: true
