
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: testapp
  namespace: argocd
spec:
  project: default
  destination:
    namespace: testapp
  sources:
    - repoURL: https://github.com/cgerull/deploy-test-server
      path: charts/testapp
      targetRevision: main
      helm:
        valueFiles:
          - deploy/reviewomgeving/testapp.yaml

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
