
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: testapp
  namespace: argocd
spec:
  project: default
  destination:
    namespace: testapp
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/cgerull/deploy-test-server
    path: charts/testapp
    targetRevision: create-testapp
    helm:
      valueFiles:
        - ../../deploy/reviewomgeving/testapp.yaml
        # parameters:
        #   - name: global.imageTag
        #     value: master-$ARGOCD_APP_REVISION
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
