---
name: Kubernetes manifests

on:
  pull_request:
    paths:
      - "charts/**"
      - "deploy**"

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@master
      - name: Generate kubernets manifests
        run: bash ./.ci-scripts/build/generate-manifests.sh all
